import argparse,hashlib,json,subprocess,sys,time
from datetime import datetime,timezone
from pathlib import Path

ALLOWED={"write_marker","spawn_echo","hash_file","sleep","cpu_burst"}
CAPS={"sleep_seconds":2.0,"cpu_seconds":1.0,"actions":20,"marker_bytes":4096}

def validate(manifest):
    if manifest.get("schema")!="lr-payload-lab/v1":raise ValueError("unsupported schema")
    actions=manifest.get("actions")
    if not isinstance(actions,list) or len(actions)>CAPS["actions"]:raise ValueError("actions must be a list with at most 20 items")
    for i,a in enumerate(actions):
        if not isinstance(a,dict) or a.get("type") not in ALLOWED:raise ValueError(f"action {i}: type is not allowed")
        if a["type"] in {"write_marker","hash_file"}:
            p=Path(str(a.get("path","")))
            if not str(p) or p.is_absolute() or ".." in p.parts:raise ValueError(f"action {i}: path must stay inside the lab workspace")
        if a["type"]=="write_marker" and len(str(a.get("content","" )).encode())>CAPS["marker_bytes"]:raise ValueError(f"action {i}: marker is too large")
        if a["type"]=="sleep" and not 0<=float(a.get("seconds",0))<=CAPS["sleep_seconds"]:raise ValueError(f"action {i}: sleep cap exceeded")
        if a["type"]=="cpu_burst" and not 0<=float(a.get("seconds",0))<=CAPS["cpu_seconds"]:raise ValueError(f"action {i}: cpu cap exceeded")
    return manifest

def safe_path(root,relative):
    root=root.resolve(); p=(root/relative).resolve()
    if p!=root and root not in p.parents:raise ValueError("path escaped workspace")
    return p

def execute(manifest,workspace,dry_run=False):
    validate(manifest); workspace.mkdir(parents=True,exist_ok=True)
    receipt={"schema":"lr-payload-receipt/v1","scenario":manifest.get("name","unnamed"),
             "started_at":datetime.now(timezone.utc).isoformat(),"dry_run":dry_run,"events":[],"rollback":[]}
    for index,a in enumerate(manifest["actions"],1):
        typ=a["type"]; event={"id":f"E{index:03d}","action":typ,"status":"planned" if dry_run else "completed"}
        if typ=="write_marker":
            p=safe_path(workspace,a["path"]); event["path"]=str(p)
            if not dry_run:p.parent.mkdir(parents=True,exist_ok=True);p.write_text(str(a.get("content","payload-lab marker")),encoding="utf-8");receipt["rollback"].append({"type":"delete","path":str(p)})
        elif typ=="spawn_echo":
            text=str(a.get("text","payload-lab"))[:256];event["argv"]=[sys.executable,"-c","print(...)"]
            if not dry_run:event["stdout"]=subprocess.run([sys.executable,"-c","import sys;print(sys.argv[1])",text],capture_output=True,text=True,timeout=3,check=True).stdout.strip()
        elif typ=="hash_file":
            p=safe_path(workspace,a["path"]);event["path"]=str(p)
            if not dry_run:event["sha256"]=hashlib.sha256(p.read_bytes()).hexdigest()
        elif typ=="sleep":
            seconds=float(a.get("seconds",0));event["seconds"]=seconds
            if not dry_run:time.sleep(seconds)
        elif typ=="cpu_burst":
            seconds=float(a.get("seconds",0));event["seconds"]=seconds
            if not dry_run:
                end=time.monotonic()+seconds;n=0
                while time.monotonic()<end:n=hashlib.sha256(str(n).encode()).digest()[0]+n
                event["iterations"]=n
        receipt["events"].append(event)
    receipt["finished_at"]=datetime.now(timezone.utc).isoformat();return receipt

def rollback(receipt,workspace):
    removed=[]
    for a in reversed(receipt.get("rollback",[])):
        if a.get("type")!="delete":continue
        p=Path(a["path"]).resolve();root=workspace.resolve()
        if p!=root and root in p.parents and p.is_file():p.unlink();removed.append(str(p))
    return removed

def build(manifest,out):
    validate(manifest)
    encoded=json.dumps(manifest,ensure_ascii=False,separators=(",",":"))
    code='''#!/usr/bin/env python3\n# Generated by LR-PayloadLab. Auditable benign scenario; standard library only.\nimport json,sys\nfrom pathlib import Path\nfrom payload_lab.cli import execute\nMANIFEST=json.loads(%r)\nif __name__=="__main__":\n print(json.dumps(execute(MANIFEST,Path(sys.argv[1] if len(sys.argv)>1 else "./payload-lab-workspace")),ensure_ascii=False,indent=2))\n'''%encoded
    out.write_text(code,encoding="utf-8");return hashlib.sha256(out.read_bytes()).hexdigest()

def main(argv=None):
    p=argparse.ArgumentParser(description="Build and run bounded, auditable research payloads")
    sub=p.add_subparsers(dest="cmd",required=True)
    for name in ("plan","run"):
        q=sub.add_parser(name);q.add_argument("manifest",type=Path);q.add_argument("--workspace",type=Path,default=Path("payload-lab-workspace"));q.add_argument("--receipt",type=Path)
    q=sub.add_parser("build");q.add_argument("manifest",type=Path);q.add_argument("--output",type=Path,required=True)
    q=sub.add_parser("rollback");q.add_argument("receipt",type=Path);q.add_argument("--workspace",type=Path,default=Path("payload-lab-workspace"))
    a=p.parse_args(argv)
    try:
        if a.cmd=="rollback":result={"removed":rollback(json.loads(a.receipt.read_text()),a.workspace)}
        else:
            manifest=validate(json.loads(a.manifest.read_text(encoding="utf-8")))
            if a.cmd=="build":result={"output":str(a.output),"sha256":build(manifest,a.output)}
            else:
                result=execute(manifest,a.workspace,a.cmd=="plan")
                if a.receipt:a.receipt.write_text(json.dumps(result,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    except (ValueError,OSError,json.JSONDecodeError,subprocess.SubprocessError) as e:p.error(str(e))
    print(json.dumps(result,ensure_ascii=False,indent=2));return 0
if __name__=="__main__":sys.exit(main())
